### ISSUE TITLE
returned values malprocessed

### ISSUE THREAD

**Issue by didenko** [creachadair/misctools#1]
Looks to me that instead of  https://github.com/creachadair/misctools/blob/b7daff122a62b8f2d7c36bb827a1f17f211625ce/group/group.go#L32-L36

This will actually work:
```go
	grp := C.getgrnam(C.CString(name))
	return unpack(grp)
```
Similarly in the other function

**Comment by creachadair** [comment]
I'm very sorry for not replying sooner, I did not notice this issue until just now. I must have accidentally turned off notifications for this repository.

The group package checks for errors intentionally, did you find a case where it doesn't work?

The two-value return idiom is supported by cgo, per https://pkg.go.dev/cmd/cgo:

> Any C function (even void functions) may be called in a multiple assignment context to retrieve both the return value (if any) and the C errno variable as an error

Since `getgrnam` et al. do set `errno` (e.g., https://man7.org/linux/man-pages/man3/getgrnam.3.html), this seems like the right thing to do (emphasis added):

> The `getgrnam()` and `getgrgid()` functions return a pointer to a group structure, or NULL if the matching entry is not found or an error occurs.  **If an error occurs, errno is set to indicate the error.**

**Comment by didenko** [comment]
No worries,

Right. C functions return a single pointer value. Which can be NULL. I understand that cgo in docs talks about multi-value assignment. For some reason, it worked in a single-value context for me and failed the way it is with two recepients. I can not share the proprietary code, but I will check again in a couple of weeks when I am on this task. May be it is something silly like `error.h` got missed. Does it run successfully for you agains an NIS installation?

Thank you for checking back.

**Comment by creachadair** [comment]
> Right. C functions return a single pointer value. Which can be NULL. I understand that cgo in docs talks about multi-value assignment. For some reason, it worked in a single-value context for me and failed the way it is with two recepients.

That's interesting. I realize you can't share the code you're working on, but can you say more about your development environment, e.g., what version of Go, what operating system? And are you able to say more about how it fails for you?

I haven't tested this code on lots of different systems, but I know it works on macOS (which is what I use) and a couple different flavours of Linux (Ubuntu, Alpine). I don't know if it would run on Windows, though maybe with WSL it might.

**Comment by creachadair** [comment]
I never did figure out exactly what was going on here, but since I've now removed this package from the repo, I'm going to go ahead and close this. 🙂
